before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl
  - pip3 install pyyaml awscli
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  # - test
  - deploy


build:
  script:
    - python3 build_helper.py docker-compose.yml > /dev/null
    - docker build -t sc-registry.fredhutch.org/labsquirrel_ssh:latest .
    # for now, push w/o testing
    - docker push sc-registry.fredhutch.org/labsquirrel_ssh:latest
 
# test:
#   script:
#     - echo write some real tests

deploy:
  stage: deploy
  only:
    refs:
        - master
  script:
    - sleep 5
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - python3 build_helper.py docker-compose.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - labsquirrel
