version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=First*4isFour
      - MYSQL_PASSWORD=Second*4isEight
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    # ports:
    #   - 80:80
    #   - 443:443
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always

  nginx:
    image: nginx
    links:
      - app
    ports:
      - 443:443
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./fhcrc.org-pub-bundled.pem:/etc/nginx/fhcrc.org-pub-bundled.pem
     - ./fhcrc.org.key:/etc/nginx/fhcrc.org.key
